usr/lib/libclangTidyRawSpeedModule.so
usr/lib/libclangTidyRawSpeedModule.so.17
usr/lib/*/cmake/RawSpeedClangTidyModule/RawSpeedClangTidyModuleConfig.cmake
usr/lib/*/cmake/RawSpeedClangTidyModule/RawSpeedClangTidyModuleConfigVersion.cmake
usr/lib/*/cmake/RawSpeedClangTidyModule/RawSpeedClangTidyModuleTargets-release.cmake
usr/lib/*/cmake/RawSpeedClangTidyModule/RawSpeedClangTidyModuleTargets.cmake
usr/lib/*/libclangTidyRawSpeedModule.so
usr/lib/*/libclangTidyRawSpeedModule.so.17
