usr/lib/libclangTidyRawSpeedModule.so
usr/lib/libclangTidyRawSpeedModule.so.17
usr/lib/*/cmake/clangTidyRawSpeedModule/clangTidyRawSpeedModuleConfig.cmake
usr/lib/*/cmake/clangTidyRawSpeedModule/clangTidyRawSpeedModuleConfigVersion.cmake
usr/lib/*/cmake/clangTidyRawSpeedModule/clangTidyRawSpeedModuleTargets-release.cmake
usr/lib/*/cmake/clangTidyRawSpeedModule/clangTidyRawSpeedModuleTargets.cmake
usr/lib/*/libclangTidyRawSpeedModule.so
usr/lib/*/libclangTidyRawSpeedModule.so.17
